# Generated by Django 2.2.12 on 2021-11-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_siswa_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='course',
            new_name='course_id',
        ),
    ]
